# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.cache/wt [current_project]
set_property parent.project_path D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/count_down_pointer.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/from_loa_to_quar.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/from_quar_to_other.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/modify_pointer.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/my_2_dff.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/my_dff.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/update_an_QUAR.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/update_an_QUAR_pos_1.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/update_an_QUAR_pos_2.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/update_an_QUAR_pos_3.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/update_fast_LOA.v
  D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/sources_1/new/Assignment.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/constrs_1/new/Constraints.xdc
set_property used_in_implementation false [get_files D:/EE2026labs/Lab4/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H/Lab4_Monday_PM_TRA_QUANG_MINH_THONG_A0200659H.srcs/constrs_1/new/Constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Assignment -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Assignment.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Assignment_utilization_synth.rpt -pb Assignment_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
